Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04-arm64"
    config.vm.hostname = "consul-server"
    config.vm.network "forwarded_port", guest: 8500, host: 8500
    config.vm.provider :vmware_desktop do |vmware|
    end
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y unzip
        wget https://releases.hashicorp.com/consul/1.18.0/consul_1.18.0_linux_arm64.zip
        unzip consul_1.18.0_linux_arm64.zip
        rm consul_1.18.0_linux_arm64.zip
        # -client "0.0.0.0": This option is set to allow connections from any IP address to the Consul client interface, 
        # useful for accessing the UI and API.
        #
        # -bind: This option tells Consul the address to bind server and client interfaces to. 
        #It's used for internal cluster communications.
        consul agent -server -ui -client=0.0.0.0 -bind=0.0.0.0
     SHELL
end